name: Deploy

# Deploys are manually triggered
on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Deploy as prerelease'
        required: true
        type: boolean

jobs:
  deploy:
    name: 'Deploy'
    environment: auto deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest # TODO: this should probably run on multiple OSes

    steps:
      - uses: actions/checkout@v3
        with:
          # Ensure that git uses your token with admin access to the repo
          token: ${{ secrets.GH_TOKEN }}

      - name: Prepare repository
        # Fetch full git history and tags
        run: git fetch --unshallow --tags

      - uses: ./.github/actions/setup

      - name: Deploy Final
        if: ${{ ! inputs.prerelease }}
        run: pnpm auto shipit -vv
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy Prerelease
        if: ${{ inputs.prerelease }}
        run: pnpm auto shipit --prerelease -vv
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
